# Generated by Django 4.0.6 on 2022-07-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('edad', models.CharField(max_length=16)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
